### ISSUE TITLE
Fix data persistence with Docker Compose

### ISSUE THREAD

**Issue by carlosplf** [carlosplf/br_data_inspector#50]
Data saved into redis and mongo containers isn't persisted.

**Comment by carlosplf** [comment]
Removed the volume folders created by docker-compose and recreated the images and containers. Seens to be resolved.

Docker-compose config used in production:

```
services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/backend-dockerfile-prod
    ports:
      - "8080:8080"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/certs:/etc/ssl/certs
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend-dockerfile-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/certs:/etc/ssl/certs

  redis:
    image: "redis"
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    command: ["redis-server", "--appendonly", "yes", "--save", "60"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
    mongo_data:
    redis_data:
```
